### ISSUE TITLE
The example does not work well 

### ISSUE THREAD

**Issue by Alii-isk** [Caldarie/flutter_tflite_audio#1]
i tested the example and it doesn't work well at recognizing the words i say.
is it the lack of dataset that causing this or is it something else ?
and please how can i create a Model can i use teachablemachine.withgoogle.com for that?

**Comment by Caldarie** [comment]
Thank you for the question Alii-isk.

You are correct. The example model (which is freely available to download from google) will not be able to pick up words well unless you speak clearly with no noticeable accent and background noise.

I believe there are several reasons why:

a) If you upload the model on [this website](https://lutzroeder.github.io/netron/), you can see that the demonstration model is very simple
b) as you've mentioned, its possible there is a lack of a comprehensive dataset for training.
c) To save processing power, the package that i wrote only accepts raw audio file as the 1st input and sample rate as the 2nd input. In a perfect world, you'd also want to extract features such as ZCR, RMSE and SF to improve accuracy. You can have your model extract MFCC if you know how to code with tensorflow.
d) As for teachablemachine.withgoogle.com, i've never used it. But as long as you set your model has the following two tensor inputs ( float32[16000,1] for raw audio data and int32[1] as the sample rate) it should work fine.

What you can do however is to increase the number of cpu threads. You could possibly increase accuracy

**Comment by Alii-isk** [comment]
thank you for your reply i really appreciate it
unfortunately i don't have much knowledge about machine learning ,i just
wanted to make a japanese Hiragana Spell checker for my app, do you know
any other way to do that

**Comment by Caldarie** [comment]
Unfortunately, I'm not aware of any definite solutions to solve your problem. Though, have you checked out machine learning platforms such as google's [cloud automl](https://cloud.google.com/automl)? You're not required to have as much indepth knowledge compared to coding by hand.

**Comment by Alii-isk** [comment]
thank you so much for your time i will definitely check automl and i would
love to see some new futures on your package
