### ISSUE TITLE
nil error running example app, decodedwav models, on iOS emulator

### ISSUE THREAD

**Issue by brannendl** [Caldarie/flutter_tflite_audio#14]
Syncing files to device iPhone 8...
Activating Dart DevTools...
tflite_audio/SwiftTfliteAudioPlugin.swift:342: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.

**Comment by Caldarie** [comment]
Hi @brannendl,

Is this problem exclusive to iOS? Or do you receive a similar error on android?

**Comment by Caldarie** [comment]
Closed due to inactivity

**Comment by brannendl** [comment]
Regarding Android emulator, I get a different error.  Both the iOS and Android errors may be due to the same cause.  In the Example app, the variable "result" is not initialized.  I marked it late to get it to run.  However, the example app needs code to initialize the variable.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following LateError was thrown building MyApp(dirty, state: _MyAppState#6e25d):
LateInitializationError: Field 'result' has not been initialized.

**Comment by Caldarie** [comment]
Hi @brannendl,

For the iOS error, it's likely that you're using the wrong input type, or that your model input is incompatible with this package. Can you upload your model on [here](https://netron.app/) and tell me the input shape?

For android, it looks like the error is from the flutter side. It's unlikely that they derived from a similar error.
