### ISSUE TITLE
Null safety: Error in example code 

### ISSUE THREAD

**Issue by Bsm-B** [Caldarie/flutter_tflite_audio#15]
I think it is caused by the addition of null safety compatibility without update the example code. 

Error: 

lib/main.dart:180:58: Error: The parameter 'result' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  Widget labelListWidget(List<String> labelList, [String result]) {     
                                                         ^^^^^^         
lib/main.dart:118:68: Error: The argument type 'List<String>?' can't be assigned to the parameter type 'List<String>' because 'List<String>?' is nullable and 'List<String>' isn't.
 - 'List' is from 'dart:core'.                                          
                              return labelListWidget(labelSnapshot.data);
                                                                   ^    
lib/main.dart:129:61: Error: The argument type 'List<String>?' can't be assigned to the parameter type 'List<String>' because 'List<String>?' is nullable and 'List<String>' isn't.
 - 'List' is from 'dart:core'.                                          
                              labelListWidget(labelSnapshot.data),      
                                                            ^           
lib/main.dart:141:49: Error: The argument type 'List<String>?' can't be assigned to the parameter type 'List<String>' because 'List<String>?' is nullable and 'List<String>' isn't.
 - 'List' is from 'dart:core'.                                          
                                  labelSnapshot.data,                   
                                                ^                       
lib/main.dart:20:33: Error: Field 'result' should be initialized because its type 'Stream<Map<dynamic, dynamic>>' doesn't allow null.
 - 'Stream' is from 'dart:async'.                                       
 - 'Map' is from 'dart:core'.                                           
  Stream<Map<dynamic, dynamic>> result;           

Flutter Version : 
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (4 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by Caldarie** [comment]
Hi @Bsm-B ,

Thanks for pointing out the error!

It seems that you are right about the null incompatibility with the example.

i will post an update soon.

**Comment by Caldarie** [comment]
Hi @Bsm-B,

I have updated the example to be null compatible. Please check if it works for you

**Comment by Bsm-B** [comment]
@Caldarie  Thank you.. It works well 🐱‍💻
