### ISSUE TITLE
Google Teachable Machine raw output returns NaN

### ISSUE THREAD

**Issue by Caldarie** [Caldarie/flutter_tflite_audio#16]
I have the same problem but only on one device. I created a model with Google Teachable Machine and tested this on two devices:

**Samsung Galaxy S9 Plus**
The first label is always detected here.
The logged raw scores are: [NaN, NaN, NaN]

**Samsung Galaxy S20**
The detection works perfectly here

Both were tested under the same conditions.

The S20 outputs a NaN in one of hundreds of cases.
The S9 always outputs NaN. I haven't yet been able to get a score on the S9.

Any suggestions?

_Originally posted by @fabian-rump in https://github.com/Caldarie/flutter_tflite_audio/issues/10#issuecomment-894099752_

**Comment by Caldarie** [comment]
@fabian-rump

Do you also get similar results for decodedWav models on both s9 and s20? Or is the problem just with google teachable machine?

**Comment by fabian-rump** [comment]
I only tried it with the google teachable machine models and rawAudio.

**Comment by Caldarie** [comment]
Hi @fabian-rump,

I am having difficulty reproducing your problem. If its not too much to ask, would you be willing to test the example with decovedWav and let me know if you see something similar? 

Also, is this problem from the example? Or from your own model?

**Comment by fabian-rump** [comment]
If I change the inputType to "decodeWav" then are:
**Samsung Galaxy S9 Plus**
Raw Scores: [0.0, 0.0, 0.0]

**Samsung Galaxy S20**
Raw Scores: [0.0, 0.0, 0.0]

And the result on both devices:
result: {hasPermission=true, inferenceTime=0, recognitionResult=0 FirstLabel}

The model was created with the Google Teachable Machine with own classes.
I also tried out the model from [here](https://carolinamalbuquerque.medium.com/audio-recognition-using-tensorflow-lite-in-flutter-application-8a4ad39964ae) and get the same results.

**Comment by Caldarie** [comment]
Hi @fabian-rump 

Im suspecting that native android tflite package hasn't been properly installed.

Can you run the following commands in the terminal

- cd ../flutter_tflite_audio/example
- flutter clean
- flutter pub get
- flutter run

Also please post the full log here on github.

Let me know if this works for you.
