### ISSUE TITLE
The plugin `tflite_audio` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by ricardo-hl** [Caldarie/flutter_tflite_audio#17]
The plugin `tflite_audio` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:

**Comment by Caldarie** [comment]
@rhernandez-itemsoft Thanks for reporting this. 

I will post an update soon.

**Comment by Caldarie** [comment]
Hi @rhernandez-itemsoft 

I have posted an update on 0.1.9. The plugin should now support Android V2 embedding.

Please let me know if you still see the error message.
