### ISSUE TITLE
Is it possible to record the audio at the same time?

### ISSUE THREAD

**Issue by joknjokn** [Caldarie/flutter_tflite_audio#21]
Hi,

I'm wondering if it's possible to record audio at the same time the model is running?

Basically, I want to build something that saves snippets of the audio when specific things are detected.

Thanks,
Jonas

**Comment by Caldarie** [comment]
hi @joknjokn,

Its possible for a model to output the starting and ending time when it detects a specific sound. However, this is based on how you train your model, not on this plugin.

As for saving the audio file, I have yet to implement this feature on this plugin, but its doable. You can manually splice the audio once you have saved the file, or edit the plugin yourself to do so asynchronously
