### ISSUE TITLE
Android Permission bug

### ISSUE THREAD

**Issue by bobosette** [Caldarie/flutter_tflite_audio#29]
Hi @Caldarie . I found another issue to fix. On my app it's the dart code which ask for permission (It asks for all the permissions inside the home page > I need to do this cause tflite_audio is not the only package that need permissions). When the app ask for the permission and user grants them, I don't know why but tflite_audio shows a dialog with this message: 'Microphone permission denied. Go to settings etc..'. But it isn't true cause user granted that permission. After a lot of time, I found the issue inside TfliteAudioPlugin.java, raw 330 (inside onRequestPermissionResult() method). I don't know why but it seems like that method doesn't understand that permission has been already granted.
Can you provide a little update on this thing?
Thank you

**Comment by Caldarie** [comment]
hi @bobosette 

Many thanks for reporting various bug. Really appreciate it.

I will investigate the issue. It seems that Java/android has been giving me alot of bugs lately compared to iOS. I may consider rewriting the whole plugin to kotlin in the future :laughing:

**Comment by bobosette** [comment]
Incredible. Usually is the opposite. Let me know if you fix it

**Comment by Caldarie** [comment]
Yeah.. i feel java is overly complicated and rigid. I end up writing perhaps 30 to 40% more code in java compared to swift..

**Comment by bobosette** [comment]
I don't know cause I didn't learn swift. Only a little bit to work with flutter platform channel.

**Comment by Caldarie** [comment]
Hi, it seems you are right. There are some strange behaviours with the master version.

Fortunately, this [branch](https://github.com/Caldarie/flutter_tflite_audio/tree/feature/inference_on_stored_audio) im working on does not seem to exhibit the same problem.

As you have a different device than I, perhaps you can test this branch for me to see if you still have the same problem?

**Comment by bobosette** [comment]
Ok I will try and I'll let you know

Il giorno mer 5 gen 2022 alle ore 16:17 Michael Nguyen <
***@***.***> ha scritto:

**Comment by Caldarie** [comment]
Thanks. Please do let me know. I do hope to publish new update very soon.

**Comment by bobosette** [comment]
It works. No more permission dialog if I granted before. Thank you

Il giorno mer 5 gen 2022 alle ore 16:51 Michael Nguyen <
***@***.***> ha scritto:

**Comment by Caldarie** [comment]
Many thanks for the test. I will release an update very soon. Includes many stability fixes as well.

**Comment by Caldarie** [comment]
Hi, i have published the new package 0.2.2+2. Please let me know if you run into any bugs.
