### ISSUE TITLE
loading the model

### ISSUE THREAD

**Issue by Malakmud** [Caldarie/flutter_tflite_audio#3]
I tried your code for teachable machine in flutter but when I run the app it keeps loading the model and I couldn't use the functionality

**Comment by Caldarie** [comment]
Hi @Malakmud,

I apologise for the late reply.

Would you be kind enough to include detailed steps to reproduce this bug?

**Comment by Caldarie** [comment]
Hi @Malakmud,

I would like to follow up on the issue.

Do you still have a problem with loading the model?

**Comment by Caldarie** [comment]
Closed due to inactivity
