### ISSUE TITLE
Real time audio recognition from raw audio values

### ISSUE THREAD

**Issue by kannel-outis** [Caldarie/flutter_tflite_audio#39]
Hi, great work here...
Please is there a way to do a real time audio recognition using the raw values gotten from an analog microphone (has gone through a little big of processing.. It works if loaded on audacity). The values are gotten from an analog microphone connected to a Raspberry pi Pico, then sent in real time to my flutter app. Please is there a way to do it with your package or just any idea on how to do it in general.

Thanks

**Comment by Caldarie** [comment]
Hi @kannel-outis,

For your use case, you will need to modify the package yourself. For [android](https://github.com/Caldarie/flutter_tflite_audio/blob/master/android/src/main/java/flutter/tflite_audio/TfliteAudioPlugin.java), assuming your raw values are of pcm16 format,  youll need to:

1. Splice your recording size to chunks that fit your model input size. For example, with a recording length is 50000 and input size is 16000, you'll get three audio chunks
2. Simply pass each chunk to the function below:
```java
private void startRecognition(short[] inputBuffer16)
```

And thats it.

**Comment by kannel-outis** [comment]
Thank you so much... I will try this.
